### ISSUE TITLE
Phase 2

### ISSUE THREAD

**Issue by andy-young** [dylanavery720/weatherly#20]
- [ ] Display likely-hood of weather event happening

- [ ] Each day should have a summary of what the weather will look like ex: Today: Sunny Today, It's currently 42, the high will be 46

- [ ] Application should handle when a user searches for a location that is not found by the API. 

- [ ] Team should research different ways to handle unfound locations by looking around on different weather and other location searching applications and implement a solution for their project that they find intuitive.
